# Generated by Django 3.2 on 2021-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='no_picture.png', upload_to='blogpage'),
        ),
    ]
