# Generated by Django 3.2 on 2021-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(choices=[('In', 'Independent'), ('EU', 'Europe'), ('Af', 'Africa'), ('US', 'United States'), ('AS', 'Asia'), ('Rus', 'Russia')], default='In', max_length=3)),
                ('stake', models.CharField(choices=[('pm', 'Precious Metals'), ('Eg', 'Energy'), ('Met', 'Metals'), ('Eq', 'Equity'), ('Cs', 'Cash')], default='pm', max_length=3)),
                ('total_price', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
