# Generated by Django 3.2 on 2021-05-27 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0004_stock_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
