# Generated by Django 3.2 on 2021-06-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0007_alter_instrument_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='region',
            field=models.CharField(choices=[('Independent', 'Independent'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('USA', 'United States'), ('Asia', 'Asia'), ('Russia', 'Russia')], max_length=13),
        ),
    ]
