# Generated by Django 3.2 on 2021-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0008_alter_instrument_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='region',
            field=models.CharField(choices=[('In', 'Independent'), ('EU', 'Europe'), ('Af', 'Africa'), ('US', 'United States'), ('AS', 'Asia'), ('Rus', 'Russia')], max_length=3),
        ),
    ]
