# Generated by Django 3.2 on 2021-06-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0009_alter_instrument_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('In', 'Independent'), ('EU', 'Europe'), ('Af', 'Africa'), ('US', 'United States'), ('AS', 'Asia'), ('Rus', 'Russia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('pm', 'Precious Metals'), ('Eg', 'Energy'), ('Met', 'Metals'), ('Eq', 'Equity'), ('Cs', 'Cash')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='stake',
        ),
        migrations.AddField(
            model_name='instrument',
            name='sector',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='region',
            field=models.CharField(default='In', max_length=20),
        ),
    ]
