# Generated by Django 3.2 on 2021-06-13 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0011_auto_20210613_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='profiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(max_length=20),
        ),
    ]
