# Generated by Django 3.2 on 2021-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0013_auto_20210613_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=120),
        ),
    ]
